### PR TITLE
Add i-Code CNES plugin for shell and fortran

### LINKED ISSUE #7: Support for Shell and Fortran
#### Is your feature request related to a problem? Please describe.

> _A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Shell and Fortran languages should be supported, like in Docker-CAT.

#### Describe the solution you'd like

> _A clear and concise description of what you want to happen._

This image should have the same plugin as Docker-CAT for shell and fortran, namely Sonar i-Code CNES plugin.

#### Describe alternatives you've considered

> _A clear and concise description of any alternative solutions or features you've considered._

### PR DESCRIPTION
**Pull request by ThomasCluzel**
## Proposed changes

> _Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

This PR adds the i-Code CNES plugin to the image to support shell and fortran like Docker-CAT.

## Types of changes

What types of changes does your code introduce to this project?
> _Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Issues closed by changes

> _List here all issues closed by your changes. Use a list of items like `- [x] Close #0`_

- [x] Close #7 

## Checklist

> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](CODE_OF_CONDUCT.md)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ThomasCluzel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/lequal/sonarqube/pullRequest?prid=5960568&bid=19543468)

**Comment by ThomasCluzel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/lequal/sonarqube/pullRequest?prid=5960568&bid=19543468)

**Comment by ThomasCluzel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/lequal/sonarqube/pullRequest?prid=5960568&bid=19543468)

**Review by begarco — APPROVED** [review]

**Comment by ThomasCluzel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/lequal/sonarqube/pullRequest?prid=5960568&bid=19543468)

**Pull request merged**
