### PR TITLE
ci: Create docker-publish.yml

### LINKED ISSUE #40: Publish recent Docker image
#### Describe the bug

The latest version of the Docker Image is 3 years old:
https://hub.docker.com/r/lequal/sonarqube/tags

#### Expected behavior

Recent version of the Docker image should be published.

### PR DESCRIPTION
**Pull request by gbonnefille**
## Proposed changes

Publish Docker images from master branch.
## Types of changes

What types of changes does your code introduce to this project?
> _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

> _List here all issues closed by your changes. Use a list of items like `- [x] Close #0`_

- [x] Close #40 

## Checklist

> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I agree with the [CODE OF CONDUCT](CODE_OF_CONDUCT.md)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gbonnefille** [comment]
@louisjdmartin any opinion on this?

**Comment by louisjdmartin** [comment]
It's planned to push everything on docker hub (currently, images on there are pretty old because... nobody push new releases => https://hub.docker.com/r/lequal/sonarqube )

@Topin2001 as you work on docker-cat CI, can you check this PR ? And eventually adapt-it to push on our docker hub registry (by changing URL and environment variables if needed)

**Comment by louisjdmartin** [comment]
PS: @gbonnefille Thanks for this PR :)

**Comment by gbonnefille** [comment]
> PS: @gbonnefille Thanks for this PR :)

You're welcome. This project is really useful and it deserve an up-to-date Docker image.

**Review by louisjdmartin — APPROVED** [review]

**Pull request merged**
